import os
BOT_TOKEN = "7144225641:AAEiEO5S0ofPreoftsuFJKiNToSWhEqNa-I"
GIGACHAT_TOKEN = "NmU5ZjRjYTgtMTQ1OC00NTE5LTk0N2EtODBiZjFiZjE3ZTcyOjVmMzNiMGQ3LWZlMzQtNDc5MC05NTgxLTQ0OTIwOWJiODRiOA=="
GIGACHAT_AUTH_KEY = "NmU5ZjRjYTgtMTQ1OC00NTE5LTk0N2EtODBiZjFiZjE3ZTcyOjVmMzNiMGQ3LWZlMzQtNDc5MC05NTgxLTQ0OTIwOWJiODRiOA=="
KANDINSKY_TOKEN = "ваш_ключ_kandinsky"
DATABASE_URL = os.getenv("DATABASE_URL")